#ifndef CONFIG_H
#define CONFIG_H

#define BAUD_RATE 115200
#define SENSOR_PIN 2

#define DEVICE_NAME "DEVICE NAME"
#define DEVICE_UUID "DEVICE UUID"

#define WIFI_SSID "WIFI SSID"
#define WIFI_PASSWORD "WIFI PASSWORD"

#define MQTT_SERVER "MQTT SERVER"
#define MQTT_PORT 8883
#define MQTT_USERNAME "MQTT USERNAME"
#define MQTT_PASSWORD "MQTT PASSWORD"
#define MQTT_EVENTS_TOPIC "MQTT EVENTS TOPIC

#endif